name: komari

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "master"
      - "v*.*.*"
    tags:
      - "v*.*.*"
    paths-ignore:
      - "**/*.md"
      - "examples/**"
      - "docs/**"
  pull_request:
    branches:
      - "main"
      - "master"
      - "v*.*.*"
    paths-ignore:
      - "**/*.md"
      - "examples/**"
      - "docs/**"

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup

      # TODO: https://github.com/DioxusLabs/dioxus/issues/3433
      # TODO: Need to add dx fmt
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
      - run: cargo test -- --no-capture
